// Code generated by protoc-gen-go. DO NOT EDIT.
// source: great.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5b44f409f9ef03, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetRequest struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetRequest) Reset()         { *m = GreetRequest{} }
func (m *GreetRequest) String() string { return proto.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()    {}
func (*GreetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5b44f409f9ef03, []int{1}
}

func (m *GreetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRequest.Unmarshal(m, b)
}
func (m *GreetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRequest.Marshal(b, m, deterministic)
}
func (m *GreetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRequest.Merge(m, src)
}
func (m *GreetRequest) XXX_Size() int {
	return xxx_messageInfo_GreetRequest.Size(m)
}
func (m *GreetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRequest proto.InternalMessageInfo

func (m *GreetRequest) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetResponse) Reset()         { *m = GreetResponse{} }
func (m *GreetResponse) String() string { return proto.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()    {}
func (*GreetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ec5b44f409f9ef03, []int{2}
}

func (m *GreetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetResponse.Unmarshal(m, b)
}
func (m *GreetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetResponse.Marshal(b, m, deterministic)
}
func (m *GreetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetResponse.Merge(m, src)
}
func (m *GreetResponse) XXX_Size() int {
	return xxx_messageInfo_GreetResponse.Size(m)
}
func (m *GreetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetResponse proto.InternalMessageInfo

func (m *GreetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetRequest)(nil), "greet.GreetRequest")
	proto.RegisterType((*GreetResponse)(nil), "greet.GreetResponse")
}

func init() { proto.RegisterFile("great.proto", fileDescriptor_ec5b44f409f9ef03) }

var fileDescriptor_ec5b44f409f9ef03 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0xcb, 0xc2, 0x30,
	0x10, 0x86, 0xe9, 0x07, 0xed, 0xd7, 0x5c, 0x15, 0x21, 0x8a, 0x88, 0x22, 0x48, 0x17, 0x05, 0xa1,
	0x43, 0x1d, 0xdd, 0x3a, 0xe8, 0xe6, 0x50, 0x37, 0x17, 0x49, 0xe5, 0x0c, 0x85, 0xfe, 0x32, 0x49,
	0xfd, 0xfb, 0xa5, 0x67, 0x2a, 0xba, 0x25, 0xcf, 0x9b, 0x7b, 0xee, 0x25, 0x10, 0x48, 0x85, 0xc2,
	0x44, 0x8d, 0xaa, 0x4d, 0xcd, 0x5d, 0xa9, 0x10, 0x4d, 0x78, 0x00, 0xff, 0xd8, 0x1d, 0xf2, 0x4a,
	0xf2, 0x25, 0xc0, 0x3d, 0x57, 0xda, 0x5c, 0x2b, 0x51, 0xe2, 0xcc, 0x59, 0x39, 0x1b, 0x96, 0x32,
	0x22, 0x27, 0x51, 0x22, 0x5f, 0x00, 0x2b, 0x44, 0x9f, 0xfe, 0x51, 0xea, 0x77, 0xa0, 0x0b, 0xc3,
	0x3d, 0x0c, 0xc8, 0x93, 0xe2, 0xa3, 0x45, 0x6d, 0xf8, 0x16, 0x7c, 0x69, 0xbd, 0x64, 0x0a, 0xe2,
	0x51, 0x44, 0x20, 0xea, 0xd7, 0xa5, 0x9f, 0x07, 0xe1, 0x1a, 0x86, 0x76, 0x58, 0x37, 0x75, 0xa5,
	0x91, 0x4f, 0xc1, 0x53, 0xa8, 0xdb, 0xc2, 0xd8, 0x16, 0xf6, 0x16, 0x27, 0xb4, 0x45, 0x98, 0x33,
	0xaa, 0x67, 0x7e, 0x43, 0x1e, 0x83, 0x4b, 0x83, 0x7c, 0xfc, 0x2d, 0xb7, 0x1d, 0xe6, 0x93, 0x5f,
	0xf8, 0x76, 0x27, 0xec, 0xf2, 0x4f, 0xb8, 0xc9, 0x32, 0x8f, 0xbe, 0x62, 0xf7, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0xe9, 0x7f, 0x54, 0x8c, 0x19, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreatServiceClient is the client API for GreatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreatServiceClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type greatServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreatServiceClient(cc *grpc.ClientConn) GreatServiceClient {
	return &greatServiceClient{cc}
}

func (c *greatServiceClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/greet.GreatService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreatServiceServer is the server API for GreatService service.
type GreatServiceServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
}

func RegisterGreatServiceServer(s *grpc.Server, srv GreatServiceServer) {
	s.RegisterService(&_GreatService_serviceDesc, srv)
}

func _GreatService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreatServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreatService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreatServiceServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreatService",
	HandlerType: (*GreatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreatService_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "great.proto",
}
