// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/hellopb.proto

package model

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Name struct {
	Firstname            string   `protobuf:"bytes,1,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,2,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c3118f0375cdb2, []int{0}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *Name) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type RequestName struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestName) Reset()         { *m = RequestName{} }
func (m *RequestName) String() string { return proto.CompactTextString(m) }
func (*RequestName) ProtoMessage()    {}
func (*RequestName) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c3118f0375cdb2, []int{1}
}

func (m *RequestName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestName.Unmarshal(m, b)
}
func (m *RequestName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestName.Marshal(b, m, deterministic)
}
func (m *RequestName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestName.Merge(m, src)
}
func (m *RequestName) XXX_Size() int {
	return xxx_messageInfo_RequestName.Size(m)
}
func (m *RequestName) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestName.DiscardUnknown(m)
}

var xxx_messageInfo_RequestName proto.InternalMessageInfo

func (m *RequestName) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type ResponseName struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseName) Reset()         { *m = ResponseName{} }
func (m *ResponseName) String() string { return proto.CompactTextString(m) }
func (*ResponseName) ProtoMessage()    {}
func (*ResponseName) Descriptor() ([]byte, []int) {
	return fileDescriptor_74c3118f0375cdb2, []int{2}
}

func (m *ResponseName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseName.Unmarshal(m, b)
}
func (m *ResponseName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseName.Marshal(b, m, deterministic)
}
func (m *ResponseName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseName.Merge(m, src)
}
func (m *ResponseName) XXX_Size() int {
	return xxx_messageInfo_ResponseName.Size(m)
}
func (m *ResponseName) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseName.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseName proto.InternalMessageInfo

func (m *ResponseName) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Name)(nil), "model.Name")
	proto.RegisterType((*RequestName)(nil), "model.requestName")
	proto.RegisterType((*ResponseName)(nil), "model.responseName")
}

func init() { proto.RegisterFile("model/hellopb.proto", fileDescriptor_74c3118f0375cdb2) }

var fileDescriptor_74c3118f0375cdb2 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0xcf, 0x48, 0xcd, 0xc9, 0xc9, 0x2f, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x05, 0x0b, 0x2a, 0x39, 0x70, 0xb1, 0xf8, 0x25, 0xe6, 0xa6, 0x0a, 0xc9, 0x70, 0x71, 0xa6,
	0x65, 0x16, 0x15, 0x97, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21,
	0x04, 0x84, 0xa4, 0xb8, 0x38, 0x72, 0x12, 0xa1, 0x92, 0x4c, 0x60, 0x49, 0x38, 0x5f, 0x49, 0x8f,
	0x8b, 0xbb, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x04, 0x6c, 0x90, 0x3c, 0x17, 0x0b, 0xdc, 0x0c,
	0x6e, 0x23, 0x6e, 0x3d, 0xb0, 0x35, 0x7a, 0x20, 0xa9, 0x20, 0xb0, 0x84, 0x92, 0x1a, 0x17, 0x4f,
	0x51, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x58, 0x83, 0x18, 0x17, 0x5b, 0x51, 0x6a, 0x71,
	0x69, 0x4e, 0x09, 0xd4, 0x5a, 0x28, 0xcf, 0xc8, 0x89, 0x8b, 0x1b, 0x24, 0x1f, 0x9c, 0x5a, 0x54,
	0x96, 0x99, 0x9c, 0x2a, 0x64, 0xcc, 0xc5, 0x11, 0x9c, 0x58, 0xe9, 0x01, 0xf2, 0x83, 0x90, 0x10,
	0xd4, 0x54, 0x24, 0x7b, 0xa5, 0x84, 0xe1, 0x62, 0x08, 0xb3, 0x9d, 0xd8, 0xa3, 0x20, 0xde, 0x4c,
	0x62, 0x03, 0x7b, 0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x5c, 0xbf, 0xec, 0x0b, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NameServiceClient interface {
	SayHello(ctx context.Context, in *RequestName, opts ...grpc.CallOption) (*ResponseName, error)
}

type nameServiceClient struct {
	cc *grpc.ClientConn
}

func NewNameServiceClient(cc *grpc.ClientConn) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) SayHello(ctx context.Context, in *RequestName, opts ...grpc.CallOption) (*ResponseName, error) {
	out := new(ResponseName)
	err := c.cc.Invoke(ctx, "/model.NameService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameServiceServer is the server API for NameService service.
type NameServiceServer interface {
	SayHello(context.Context, *RequestName) (*ResponseName, error)
}

func RegisterNameServiceServer(s *grpc.Server, srv NameServiceServer) {
	s.RegisterService(&_NameService_serviceDesc, srv)
}

func _NameService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.NameService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).SayHello(ctx, req.(*RequestName))
	}
	return interceptor(ctx, in, info, handler)
}

var _NameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _NameService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/hellopb.proto",
}
